/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Finnovate Sales API
 * API documentation for Finnovate Sales
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  OAuthCallbackRequest,
  OAuthCallbackResponse
} from '../../schemas';





export type postAuthGoogleResponse302 = {
  data: void
  status: 302
}

;
export type postAuthGoogleResponseError = (postAuthGoogleResponse302) & {
  headers: Headers;
};

export type postAuthGoogleResponse = (postAuthGoogleResponseError)

export const getPostAuthGoogleUrl = () => {


  

  return `/auth/google`
}

export const postAuthGoogle = async ( options?: RequestInit): Promise<postAuthGoogleResponse> => {
  
  const res = await fetch(getPostAuthGoogleUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postAuthGoogleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postAuthGoogleResponse
}
  



export const getPostAuthGoogleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthGoogle>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthGoogle>>, TError,void, TContext> => {

const mutationKey = ['postAuthGoogle'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthGoogle>>, void> = () => {
          

          return  postAuthGoogle(fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthGoogleMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthGoogle>>>
    
    export type PostAuthGoogleMutationError = void

    export const usePostAuthGoogle = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthGoogle>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthGoogle>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAuthGoogleMutationOptions(options), queryClient);
    }
    export type postAuthGoogleCallbackResponse200 = {
  data: OAuthCallbackResponse
  status: 200
}

export type postAuthGoogleCallbackResponse400 = {
  data: void
  status: 400
}

export type postAuthGoogleCallbackResponse500 = {
  data: void
  status: 500
}

export type postAuthGoogleCallbackResponseSuccess = (postAuthGoogleCallbackResponse200) & {
  headers: Headers;
};
export type postAuthGoogleCallbackResponseError = (postAuthGoogleCallbackResponse400 | postAuthGoogleCallbackResponse500) & {
  headers: Headers;
};

export type postAuthGoogleCallbackResponse = (postAuthGoogleCallbackResponseSuccess | postAuthGoogleCallbackResponseError)

export const getPostAuthGoogleCallbackUrl = () => {


  

  return `/auth/google/callback`
}

export const postAuthGoogleCallback = async (oAuthCallbackRequest: OAuthCallbackRequest, options?: RequestInit): Promise<postAuthGoogleCallbackResponse> => {
  
  const res = await fetch(getPostAuthGoogleCallbackUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oAuthCallbackRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postAuthGoogleCallbackResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postAuthGoogleCallbackResponse
}
  



export const getPostAuthGoogleCallbackMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthGoogleCallback>>, TError,{data: OAuthCallbackRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthGoogleCallback>>, TError,{data: OAuthCallbackRequest}, TContext> => {

const mutationKey = ['postAuthGoogleCallback'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthGoogleCallback>>, {data: OAuthCallbackRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthGoogleCallback(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthGoogleCallbackMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthGoogleCallback>>>
    export type PostAuthGoogleCallbackMutationBody = OAuthCallbackRequest
    export type PostAuthGoogleCallbackMutationError = void

    export const usePostAuthGoogleCallback = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthGoogleCallback>>, TError,{data: OAuthCallbackRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthGoogleCallback>>,
        TError,
        {data: OAuthCallbackRequest},
        TContext
      > => {
      return useMutation(getPostAuthGoogleCallbackMutationOptions(options), queryClient);
    }
    