/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Finnovate Sales API
 * API documentation for Finnovate Sales
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiAuthMe200,
  OAuthCallbackRequest,
  OAuthCallbackResponse,
  RefreshTokenResponse,
  RequestGoogleOAuthResponse
} from '../../schemas';

import { customFetch } from '.././custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type postApiAuthGoogleResponse200 = {
  data: RequestGoogleOAuthResponse
  status: 200
}

export type postApiAuthGoogleResponseSuccess = (postApiAuthGoogleResponse200) & {
  headers: Headers;
};
;

export type postApiAuthGoogleResponse = (postApiAuthGoogleResponseSuccess)

export const getPostApiAuthGoogleUrl = () => {


  

  return `/api/auth/google`
}

export const postApiAuthGoogle = async ( options?: RequestInit): Promise<postApiAuthGoogleResponse> => {
  
  return customFetch<postApiAuthGoogleResponse>(getPostApiAuthGoogleUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  



export const getPostApiAuthGoogleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthGoogle>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthGoogle>>, TError,void, TContext> => {

const mutationKey = ['postApiAuthGoogle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthGoogle>>, void> = () => {
          

          return  postApiAuthGoogle(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthGoogleMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthGoogle>>>
    
    export type PostApiAuthGoogleMutationError = unknown

    export const usePostApiAuthGoogle = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthGoogle>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthGoogle>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiAuthGoogleMutationOptions(options), queryClient);
    }
    export type postApiAuthGoogleCallbackResponse200 = {
  data: OAuthCallbackResponse
  status: 200
}

export type postApiAuthGoogleCallbackResponse400 = {
  data: void
  status: 400
}

export type postApiAuthGoogleCallbackResponse500 = {
  data: void
  status: 500
}

export type postApiAuthGoogleCallbackResponseSuccess = (postApiAuthGoogleCallbackResponse200) & {
  headers: Headers;
};
export type postApiAuthGoogleCallbackResponseError = (postApiAuthGoogleCallbackResponse400 | postApiAuthGoogleCallbackResponse500) & {
  headers: Headers;
};

export type postApiAuthGoogleCallbackResponse = (postApiAuthGoogleCallbackResponseSuccess | postApiAuthGoogleCallbackResponseError)

export const getPostApiAuthGoogleCallbackUrl = () => {


  

  return `/api/auth/google/callback`
}

export const postApiAuthGoogleCallback = async (oAuthCallbackRequest: OAuthCallbackRequest, options?: RequestInit): Promise<postApiAuthGoogleCallbackResponse> => {
  
  return customFetch<postApiAuthGoogleCallbackResponse>(getPostApiAuthGoogleCallbackUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oAuthCallbackRequest,)
  }
);}
  



export const getPostApiAuthGoogleCallbackMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthGoogleCallback>>, TError,{data: OAuthCallbackRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthGoogleCallback>>, TError,{data: OAuthCallbackRequest}, TContext> => {

const mutationKey = ['postApiAuthGoogleCallback'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthGoogleCallback>>, {data: OAuthCallbackRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthGoogleCallback(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthGoogleCallbackMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthGoogleCallback>>>
    export type PostApiAuthGoogleCallbackMutationBody = OAuthCallbackRequest
    export type PostApiAuthGoogleCallbackMutationError = void

    export const usePostApiAuthGoogleCallback = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthGoogleCallback>>, TError,{data: OAuthCallbackRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthGoogleCallback>>,
        TError,
        {data: OAuthCallbackRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthGoogleCallbackMutationOptions(options), queryClient);
    }
    export type getApiAuthMeResponse200 = {
  data: GetApiAuthMe200
  status: 200
}

export type getApiAuthMeResponse404 = {
  data: void
  status: 404
}

export type getApiAuthMeResponseSuccess = (getApiAuthMeResponse200) & {
  headers: Headers;
};
export type getApiAuthMeResponseError = (getApiAuthMeResponse404) & {
  headers: Headers;
};

export type getApiAuthMeResponse = (getApiAuthMeResponseSuccess | getApiAuthMeResponseError)

export const getGetApiAuthMeUrl = () => {


  

  return `/api/auth/me`
}

export const getApiAuthMe = async ( options?: RequestInit): Promise<getApiAuthMeResponse> => {
  
  return customFetch<getApiAuthMeResponse>(getGetApiAuthMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetApiAuthMeQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }

    
export const getGetApiAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthMe>>> = ({ signal }) => getApiAuthMe({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthMe>>>
export type GetApiAuthMeQueryError = void


export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type postApiAuthRefreshResponse200 = {
  data: RefreshTokenResponse
  status: 200
}

export type postApiAuthRefreshResponse400 = {
  data: void
  status: 400
}

export type postApiAuthRefreshResponseSuccess = (postApiAuthRefreshResponse200) & {
  headers: Headers;
};
export type postApiAuthRefreshResponseError = (postApiAuthRefreshResponse400) & {
  headers: Headers;
};

export type postApiAuthRefreshResponse = (postApiAuthRefreshResponseSuccess | postApiAuthRefreshResponseError)

export const getPostApiAuthRefreshUrl = () => {


  

  return `/api/auth/refresh`
}

export const postApiAuthRefresh = async ( options?: RequestInit): Promise<postApiAuthRefreshResponse> => {
  
  return customFetch<postApiAuthRefreshResponse>(getPostApiAuthRefreshUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  



export const getPostApiAuthRefreshMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,void, TContext> => {

const mutationKey = ['postApiAuthRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRefresh>>, void> = () => {
          

          return  postApiAuthRefresh(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRefresh>>>
    
    export type PostApiAuthRefreshMutationError = void

    export const usePostApiAuthRefresh = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRefresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiAuthRefreshMutationOptions(options), queryClient);
    }
    export type postApiAuthLogoutResponse200 = {
  data: void
  status: 200
}

export type postApiAuthLogoutResponseSuccess = (postApiAuthLogoutResponse200) & {
  headers: Headers;
};
;

export type postApiAuthLogoutResponse = (postApiAuthLogoutResponseSuccess)

export const getPostApiAuthLogoutUrl = () => {


  

  return `/api/auth/logout`
}

export const postApiAuthLogout = async ( options?: RequestInit): Promise<postApiAuthLogoutResponse> => {
  
  return customFetch<postApiAuthLogoutResponse>(getPostApiAuthLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  



export const getPostApiAuthLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogout>>, TError,void, TContext> => {

const mutationKey = ['postApiAuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogout>>, void> = () => {
          

          return  postApiAuthLogout(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogout>>>
    
    export type PostApiAuthLogoutMutationError = unknown

    export const usePostApiAuthLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiAuthLogoutMutationOptions(options), queryClient);
    }
    