/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Finnovate Sales API
 * API documentation for Finnovate Sales
 * OpenAPI spec version: 1.0.0
 */
import type { OAuthCallbackResponseUser } from './oAuthCallbackResponseUser';

export interface OAuthCallbackResponse {
  success: boolean;
  user?: OAuthCallbackResponseUser;
}
