/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Finnovate Sales API
 * API documentation for Finnovate Sales
 * OpenAPI spec version: 1.0.0
 */

export type OAuthCallbackResponseUser = {
  id: number;
  email: string;
  name?: string;
  profilePicture?: string;
};
